# require 'rubygems'
# require 'bundler/setup'

desc "install the gem"
task :install => [:build] do
    puts "install the gem"
    sh "gem install toolbox*.gem"
end

desc "build the gem"
task :build do
    puts "start building the gem"
    sh "gem build toolbox.gemspec"
end

desc "clear the gem"
task :clear do
    puts "clear gem"
    sh "rm toolbox-*.gem"
end

desc "uninstall the gem"
task :uninstall => [:clear] do
    puts "uninstall gem"
    sh "gem uninstall -aIx toolbox"
end