require 'rubygems'
require 'bundler/setup'

task :default => :mac_and_cheese

desc "make some mac and cheess"
task :mac_and_cheese => [:boil_water, :buy_pasta, :buy_cheese] do
    puts "Making Mac & Cheese"
end

desc "buy some cheese"
task :buy_cheese => [:go_to_store] do
    puts "Buying Cheese"
end

task :buy_pasta => [:go_to_store] do
    puts "Buying Pasta"
end

task :boil_water => [:buy_pasta, :buy_cheese] do
    puts "Boiling Water"
end

task :go_to_store do
    puts "Going to the Store"
end

namespace :apple do
    task :go_to_store do
        puts "Going to the Apple Store"
    end
end

task :test_shell do
    sh 'echo "hello world"'
end